### ISSUE TITLE
Apparmor Problems with current snap

### ISSUE THREAD

**Issue by anlx-sw** [kubiko/wekan-snap#3]
Hi

I tried to run the snap package from uapp:
https://uappexplorer.com/app/wekan-ondra.ondra

Running on 
```
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```

Fresh server install - just added snapd

Two problems with it so far:
I could only set the config-variables in lowercase (with "-" instead of "_")
e.g.
working:
`sudo snap set wekan-ondra mail-url='smtp://10.10.10.50:25/'`
not working:
`sudo snap set wekan-ondra MAIL_URL='smtp://10.10.10.50:25/'`

When i try to register my first user i never get a mail.
I think there might be problems with the apparmor configuration:
```
Mar 28 19:17:35 myservername systemd[1]: Started A high performance web server and a reverse proxy server.
Mar 28 19:17:40 myservername kernel: [ 1914.026448] audit_printk_skb: 33 callbacks suppressed
Mar 28 19:17:40 myservername kernel: [ 1914.026451] audit: type=1400 audit(1490721460.381:321): apparmor="DENIED" operation="open" profile="snap.wekan-ondra.wekan" name="/" pid=20064 comm="node" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Mar 28 19:17:40 myservername kernel: [ 1914.504255] audit: type=1400 audit(1490721460.861:322): apparmor="DENIED" operation="open" profile="snap.wekan-ondra.wekan" name="/" pid=20064 comm="node" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Mar 28 19:17:40 myservername kernel: [ 1914.510609] audit: type=1400 audit(1490721460.865:323): apparmor="DENIED" operation="open" profile="snap.wekan-ondra.wekan" name="/" pid=20064 comm="node" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Mar 28 19:17:40 myservername kernel: [ 1914.513889] audit: type=1400 audit(1490721460.869:324): apparmor="DENIED" operation="open" profile="snap.wekan-ondra.wekan" name="/" pid=20064 comm="node" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Mar 28 19:17:40 myservername kernel: [ 1914.524127] audit: type=1400 audit(1490721460.881:325): apparmor="DENIED" operation="open" profile="snap.wekan-ondra.wekan" name="/" pid=20064 comm="node" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Mar 28 19:17:40 myservername kernel: [ 1914.573263] audit: type=1400 audit(1490721460.929:326): apparmor="DENIED" operation="open" profile="snap.wekan-ondra.wekan" name="/" pid=20064 comm="node" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Mar 28 19:17:40 myservername kernel: [ 1914.584923] audit: type=1400 audit(1490721460.941:327): apparmor="DENIED" operation="open" profile="snap.wekan-ondra.wekan" name="/" pid=20064 comm="node" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Mar 28 19:17:41 myservername kernel: [ 1914.759035] audit: type=1400 audit(1490721461.113:328): apparmor="DENIED" operation="open" profile="snap.wekan-ondra.wekan" name="/" pid=20064 comm="node" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Mar 28 19:18:01 myservername kernel: [ 1934.941734] audit: type=1400 audit(1490721481.296:329): apparmor="DENIED" operation="open" profile="snap.wekan-ondra.wekan" name="/" pid=20064 comm="node" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Mar 28 19:18:26 myservername snap[20055]: Exception while invoking method 'ATCreateUserServer' Error: getaddrinfo ESRCH
Mar 28 19:18:26 myservername snap[20055]:     at Object.Future.wait (/snap/wekan-ondra/46/programs/server/node_modules/fibers/future.js:449:15)
Mar 28 19:18:26 myservername snap[20055]:     at smtpSend (packages/email/email.js:89:1)
Mar 28 19:18:26 myservername snap[20055]:     at Object.Email.send (packages/email/email.js:192:1)
Mar 28 19:18:26 myservername snap[20055]:     at AccountsServer.Accounts.sendVerificationEmail (packages/accounts-password/password_server.js:797:9)
Mar 28 19:18:26 myservername snap[20055]:     at [object Object].Meteor.methods.ATCreateUserServer (packages/useraccounts_core/lib/server_methods.js:119:1)
Mar 28 19:18:26 myservername snap[20055]:     at packages/check/match.js:107:1
Mar 28 19:18:26 myservername snap[20055]:     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
Mar 28 19:18:26 myservername snap[20055]:     at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:106:1)
Mar 28 19:18:26 myservername snap[20055]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1708:18)
Mar 28 19:18:26 myservername snap[20055]:     at packages/ddp-server/livedata_server.js:711:19
Mar 28 19:18:26 myservername snap[20055]:     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
Mar 28 19:18:26 myservername snap[20055]:     at packages/ddp-server/livedata_server.js:709:40
Mar 28 19:18:26 myservername snap[20055]:     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
Mar 28 19:18:26 myservername snap[20055]:     at packages/ddp-server/livedata_server.js:707:46
Mar 28 19:18:26 myservername snap[20055]:     at tryCallTwo (/snap/wekan-ondra/46/programs/server/npm/node_modules/meteor/promise/node_modules/promise/lib/core.js:45:5)
Mar 28 19:18:26 myservername snap[20055]:     at doResolve (/snap/wekan-ondra/46/programs/server/npm/node_modules/meteor/promise/node_modules/promise/lib/core.js:200:13)
Mar 28 19:18:26 myservername snap[20055]:     - - - - -
Mar 28 19:18:26 myservername snap[20055]:     at errnoException (dns.js:37:11)
Mar 28 19:18:26 myservername snap[20055]:     at Object.onanswer [as oncomplete] (dns.js:126:16)
Mar 28 19:20:23 myservername kernel: [ 2077.534188] audit: type=1400 audit(1490721623.890:330): apparmor="DENIED" operation="open" profile="snap.wekan-ondra.wekan" name="/" pid=20064 comm="node" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Mar 28 19:20:24 myservername kernel: [ 2077.717299] audit: type=1400 audit(1490721624.074:331): apparmor="DENIED" operation="open" profile="snap.wekan-ondra.wekan" name="/" pid=20064 comm="node" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```

**Comment by kubiko** [comment]
Hi
first problem is really just outdated description in the app description which I have fixed now.
You should run $ wekan-ondra.help
I had to change key syntax to comply with new snapd rules for keys. Description was still referring to old more loose syntax.

Second issue is different. I'm not even convinced it's apparmor denial what is causing fail with email. But to be sure, can you install wekan in devmode to rule it out?
$ snap install wekan-ondra — devmode
then run your test. If it works then let me please know and we will need to look what interfaces to enable to fix it. From denial it looks like it's just trying to read root, which should be harmless, but also should not really be needed by wekan anyway….

If it still fails in devmode, then I'd suggest to contact somebody from wekan project to look into it. As I'm don't really know much about wekan myself. I only snapped it to make it more accessible to wider public.

BTW remember to revert --devmode install, as snaps in devmode won't be auto updated

**Comment by anlx-sw** [comment]
hi,

thanks.

i just reinstalled the snapwith:
`snap install wekan-ondra --devmode`
 and still get the same error.

i tried to send emails over the mailserver from the wekan server via telnet.
this worked without problems.
```
root@srv01:/home/ladmin# telnet 10.100.11.50 25
Trying 10.100.11.50...
Connected to 10.100.11.50.
.....
ehlo test.at
....
mail from:<kanban@domain.local>
250 2.1.0 Sender OK
rcpt to:<myuser@domain.local>
250 2.1.5 Recipient OK
data
354 Start mail input; end with <CRLF>.<CRLF>
test
.
250 2.6.0 <1653cdf75c0f40bd969aea100fe35f83@mailserver.domain.local> [InternalId=64141041598533, Hostname=mailserver.domain.local] Queued mail for delivery

```
if i try to register my first user i still get the error.

```
Mar 29 15:47:26 srv01 /usr/bin/snap[21854]: cmd.go:111: DEBUG: restarting into "/snap/core/current/usr/bin/snap"
Mar 29 15:47:26 srv01 snap[21854]: using default value: MONGODB_PORT='27019'
Mar 29 15:47:26 srv01 snap[21854]: using default value: MONGODB_BIND_IP='127.0.0.1'
Mar 29 15:47:26 srv01 snap[21854]: MAIL_URL='smtp://wekan:password@10.100.11.50:25/'
Mar 29 15:47:26 srv01 snap[21854]: MAIL_FROM='kanban@domain.com'
Mar 29 15:47:26 srv01 snap[21854]: ROOT_URL='https://kanban.domain.com'
Mar 29 15:47:26 srv01 snap[21854]: PORT='3000'
Mar 29 15:47:27 srv01 kernel: [75700.915812] audit_printk_skb: 207 callbacks suppressed
Mar 29 15:47:27 srv01 kernel: [75700.915815] audit: type=1400 audit(1490795247.269:676): apparmor="ALLOWED" operation="open" profile="snap.wekan-ondra.wekan" name="/" pid=21865 comm="node" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Mar 29 15:48:52 srv01 snap[21854]: Exception while invoking method 'ATCreateUserServer' Error: getaddrinfo ESRCH
Mar 29 15:48:52 srv01 snap[21854]:     at Object.Future.wait (/snap/wekan-ondra/46/programs/server/node_modules/fibers/future.js:449:15)
Mar 29 15:48:52 srv01 snap[21854]:     at smtpSend (packages/email/email.js:89:1)
Mar 29 15:48:52 srv01 snap[21854]:     at Object.Email.send (packages/email/email.js:192:1)
Mar 29 15:48:52 srv01 snap[21854]:     at AccountsServer.Accounts.sendVerificationEmail (packages/accounts-password/password_server.js:797:9)
Mar 29 15:48:52 srv01 snap[21854]:     at [object Object].Meteor.methods.ATCreateUserServer (packages/useraccounts_core/lib/server_methods.js:119:1)
Mar 29 15:48:52 srv01 snap[21854]:     at packages/check/match.js:107:1
Mar 29 15:48:52 srv01 snap[21854]:     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
Mar 29 15:48:52 srv01 snap[21854]:     at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:106:1)
Mar 29 15:48:52 srv01 snap[21854]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1708:18)
Mar 29 15:48:52 srv01 snap[21854]:     at packages/ddp-server/livedata_server.js:711:19
Mar 29 15:48:52 srv01 snap[21854]:     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
Mar 29 15:48:52 srv01 snap[21854]:     at packages/ddp-server/livedata_server.js:709:40
Mar 29 15:48:52 srv01 snap[21854]:     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
Mar 29 15:48:52 srv01 snap[21854]:     at packages/ddp-server/livedata_server.js:707:46
Mar 29 15:48:52 srv01 snap[21854]:     at tryCallTwo (/snap/wekan-ondra/46/programs/server/npm/node_modules/meteor/promise/node_modules/promise/lib/core.js:45:5)
Mar 29 15:48:52 srv01 snap[21854]:     at doResolve (/snap/wekan-ondra/46/programs/server/npm/node_modules/meteor/promise/node_modules/promise/lib/core.js:200:13)
Mar 29 15:48:52 srv01 snap[21854]:     - - - - -
Mar 29 15:48:52 srv01 snap[21854]:     at errnoException (dns.js:37:11)
Mar 29 15:48:52 srv01 snap[21854]:     at Object.onanswer [as oncomplete] (dns.js:126:16)
```

i now try to create an issue at the wekan git repo referencing this issue here as i'm not an expert at snap nor wekan - just an enthusiastic user ;-)

**Comment by kubiko** [comment]
hmm, then you will need to seek help from wekan developers, if there is missing settings or what is causing the issue. Sorry for trouble but I don't know much about wekan internals.
if fix requires some changes to snap package I'm happy to fix that

**Comment by anlx-sw** [comment]
thanks for your help. i just opened the issue at the wekan repo:
https://github.com/wekan/wekan/issues/951

**Comment by anlx-sw** [comment]
hi - i got the first response:
Can you check what MAIL_URL AND MAIL_FROM are in the env of whereever it is running?

I tried to check this with 

```
root@srvkanban01:/home/ladmin# snap run --shell wekan-ondra.status
root@srvkanban01:/home/ladmin# env
TERM=xterm
SNAP_USER_COMMON=/root/snap/wekan-ondra/common
SHELL=/bin/bash
SNAP_REEXEC=
USER=root
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd                                                     =40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;4                                                     4:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;                                                     31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7                                                     z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=0                                                     1;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz                                                     =01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*                                                     .rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;3                                                     1:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm                                                     =01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:                                                     *.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=0                                                     1;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*                                                     .m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;                                                     35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=                                                     01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.o                                                     gv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36                                                     :*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=0                                                     0;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
SUDO_USER=ladmin
SUDO_UID=1000
SNAP_LIBRARY_PATH=/var/lib/snapd/lib/gl:/var/lib/snapd/void
USERNAME=root
SNAP_COMMON=/var/snap/wekan-ondra/common
SNAP_DID_REEXEC=1
SNAP_USER_DATA=/root/snap/wekan-ondra/46
SNAP_DATA=/var/snap/wekan-ondra/46
PATH=/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
MAIL=/var/mail/root
PWD=/home/ladmin
LANG=de_AT.UTF-8
SNAP_REVISION=46
SUDO_COMMAND=/bin/su
HOME=/root/snap/wekan-ondra/46
SHLVL=2
SNAP_NAME=wekan-ondra
LANGUAGE=de_AT:de
LOGNAME=root
LESSOPEN=| /usr/bin/lesspipe %s
SNAP_ARCH=amd64
SNAP_VERSION=0.16
XDG_RUNTIME_DIR=/run/user/0/snap.wekan-ondra
SUDO_GID=1000
SNAP=/snap/wekan-ondra/46
LESSCLOSE=/usr/bin/lesspipe %s %s
_=/usr/bin/env
root@srvkanban01:/home/ladmin#
```

i don't see any environment variables like MAIL_URL  in there.
Might this be the problem?
Or am I looking at the wrong environment variables here?

**Comment by kubiko** [comment]
if you run $ wekan-ondra.help
there you can see all the supported variables. 
If you want to see how those are mapped to final names, then run:
$ snap run --shell wekan-ondra.help
$ source ${SNAP}/bin/wekan-read-settings 
this will print you and updates env variable in current shell

**Comment by anlx-sw** [comment]
thanks for your help troubleshooting the problem
it was an issue of wekan itself which is fixed with the current build.

**Comment by kubiko** [comment]
cool, I just updated to release 0.18 trying to keep up with wekan releases.

**Comment by anlx-sw** [comment]
yes my snap auto updated without any issue. thanks for your work.

**Comment by anlx-sw** [comment]
i created a small backup script for the mongodb of the wekan-ondra snap:
https://gist.github.com/anlx-sw/b10af6be3a65a09ee5082f098bb00af0

i don't know where i should commit this in the repo - maybe you can link it where it is appropriate.
